Repository symbiote/silverstripe-queuedjobs, pull requests merged in 2019-05, with the labels that each got.

#244 minor - log information to info instead of error
  src/Services/QueuedJobService.php
Labels: affects/v4, change/patch, feedback-required/core-team

#247 Extensibility options improvements.
  src/Services/AbstractQueuedJob.php
  src/Services/QueuedJob.php
  src/Services/QueuedJobService.php
  src/Tasks/Engines/DoormanRunner.php
Labels: affects/v4, change/minor

#246 3.0 - Check Subsite class exists before checking SubsiteID
  code/services/QueuedJobService.php
Labels: affects/v3, change/patch

#243 Fix mutex
  code/services/QueuedJobService.php
Labels: affects/v3, change/patch

#248 Queued only tasks configuration added.
  src/Controllers/QueuedTaskRunner.php
Labels: affects/v4, change/minor
